# Generated by Django 4.0.2 on 2022-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(choices=[('Менеджер', 'Менеджер'), ('Агент', 'Агент'), ('Администратор', 'Администратор'), ('Бухгалтер', 'Бухгалтер')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
    ]
