# Generated by Django 4.0.2 on 2022-03-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
    ]
