# Generated by Django 4.0.2 on 2022-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Обычный', 'Обычный'), ('Привилегированный', 'Привилегированный'), ('VIP', 'VIP')], max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(choices=[('Ж', 'женский'), ('М', 'мужской')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='International_passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=255)),
                ('passport_number', models.IntegerField(max_length=11)),
                ('nationality', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('date_of_issue', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'international_passport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Russian_passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.IntegerField(max_length=11)),
                ('passport_number', models.IntegerField(max_length=11)),
                ('date_of_issue', models.DateField()),
                ('expiration_date', models.DateField()),
                ('issuing_authority', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'russian_passport',
                'managed': False,
            },
        ),
    ]
